Criacao da Guia de contribuicao na wiki
Feudo-Laranja-ave-do-paraiso-DS-2021-2/wiki pull request #16
Opened 2022-02-08 14:34 UTC by marcusmartinsxx

Authored by: Marcus Martins <marcusmartinsxx@users.noreply.github.com>

Co-authored-by: Victor-oss <Victor-oss@users.noreply.github.com>

2022-02-09 00:45 UTC, lievertom requested changes
Falta referenciar o guia de conduta no arquivo mkdocs.yml

2022-02-09 00:45 UTC, lievertom commented on .github/CONTRIBUTION.md
> +Antes de realizar uma contribuição, conheça um pouco sobre o Feudo Laranja Ave do Paraíso na nossa [documentação](https://feudo-laranja-ave-do-paraiso-ds-2021-2.github.io/wiki/management/methodology-
pode redirecionar pra home da wiki: https://feudo-laranja-ave-do-paraiso-ds-2021-2.github.io/wiki/

2022-02-09 00:45 UTC, lievertom commented on docs/project/CONTRIBUTION.md
> +Antes de realizar uma contribuição, conheça um pouco sobre o Feudo Laranja Ave do Paraíso na nossa [documentação](https://feudo-laranja-ave-do-paraiso-ds-2021-2.github.io/wiki/management/methodology-
usar o link para home: https://feudo-laranja-ave-do-paraiso-ds-2021-2.github.io/wiki/

2022-02-09 00:56 UTC, marcusmartinsxx commented on .github/CONTRIBUTION.md
> +Antes de realizar uma contribuição, conheça um pouco sobre o Feudo Laranja Ave do Paraíso na nossa [documentação](https://feudo-laranja-ave-do-paraiso-ds-2021-2.github.io/wiki/management/methodology-
Eu tinha pensado nisso, ficamos em duvida na hora mas decidimos seguir o que estava texto.

2022-02-09 11:47 UTC, Victor-oss commented
Mudanças realizadas

2022-02-09 11:58 UTC, lievertom requested changes
O nome do arquivos deve  ser CONTRIBUTING.md

2022-02-09 11:58 UTC, lievertom commented on mkdocs.yml
> +    - Guia de Conduta: "https://feudo-laranja-ave-do-paraiso-ds-2021-2.github.io/wiki/"
O guia de contribuição, não guia de contuda, deve ficar na aba projeto e deve ser feita a referencia para a localização do documento:

```
    nav:
        - Ger ....
        - Projeto:
            -  Guia de contribuição: "project/CONTRIBUTING.md"
```

2022-02-09 13:09 UTC, marcusmartinsxx commented on mkdocs.yml
> +    - Guia de Conduta: "https://feudo-laranja-ave-do-paraiso-ds-2021-2.github.io/wiki/"
Feito!

2022-02-09 18:08 UTC, lievertom commented on mkdocs.yml
> +    - Guia de Conduta: "https://feudo-laranja-ave-do-paraiso-ds-2021-2.github.io/wiki/"
faltou adicionar a aba projeto e nela adicionar o guia de contribuição

2022-02-10 01:03 UTC, lievertom approved these changes
:+1:

2022-02-10 01:03 UTC, merged